allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  es5-ext: true
  gatsby: true
  gatsby-cli: true
  gdal: true
  lmdb: false
  msgpackr-extract: false
  sharp: true
  sqlite3: true
