---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  This template enable the resources

### Init Parameters
Parameters:
  AppName:
    Type: String
    Default: 'grabarte'
    Description: Application name, used for create resources
  Environment:
    Description: Environment type
    Type: String
    Default: prod
    AllowedValues: [ dev, stg, prod ]
  S3BucketName:
    Description: Environment type
    Type: String
    Default: grabarte.mx
  ArchitecturesVar:
    Type: String
    Default: x86_64
    AllowedValues:
      - x86_64
      - arm64
  CreateAWSInfra:
    Description: Create AWS Infrastructure
    Type: String
    Default: "true"
    AllowedValues: [ "true", "false" ]
  CreateDocs:
    Description: Create JS Docs
    Type: String
    Default: "false"
    AllowedValues: [ "true", "false" ]
  LastUpdate:
    Type: String
    Description: Fecha y hora de última actualización del template
Conditions:
  CreateDocsResources: !Equals
    - !Ref CreateDocs
    - "true"


Resources:
  S3PublicBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BucketName}'
      WebsiteConfiguration:
        ErrorDocument: '404.html'
        IndexDocument: 'index.html'
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      AccessControl: AwsExecRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Servicio
          Value: !Sub '${AppName}'
        - Key: Environment
          Value: !Sub '${Environment}'
  S3BucketDocs:
    Type: AWS::S3::Bucket
    Condition: CreateDocsResources
    Properties:
      BucketName: !Sub 'docs-${S3BucketName}'
      WebsiteConfiguration:
        ErrorDocument: '404.html'
        IndexDocument: 'index.html'
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      AccessControl: AwsExecRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Servicio
          Value: !Sub '${AppName}'
        - Key: Environment
          Value: !Sub '${Environment}'

Outputs:
  S3Bucket:
    Description: S3Bucket
    Value: !Ref 'S3Bucket'
  LastUpdate:
    Description: Fecha y hora de última actualización del template
    Value: !Ref 'LastUpdate'
  S3BucketPublicURL:
    Description: URL publica del bucket S3 principal
    Value: !Sub 'http://${S3Bucket}.s3-website-${AWS::Region}.amazonaws.com/'
  S3BucketDocs:
    Description: S3BucketDocs
    Value: !Ref 'S3BucketDocs'
    Condition: CreateDocsResources
  S3BucketDocsPublicURL:
    Description: URL publica del bucket S3 de documentación
    Value: !Sub 'http://docs-${S3BucketName}.s3-website-${AWS::Region}.amazonaws.com/'
    Condition: CreateDocsResources
