# curl -X GET "https://api.cloudflare.com/client/v4/accounts/[CLOUDFLARE_ID_ACCOUNT]/tokens/verify"
#     -H "Authorization: Bearer [CLOUDFLARE_TOKEN]"
GET https://api.cloudflare.com/client/v4/accounts/{{CLOUDFLARE_ID_ACCOUNT}}/tokens/verify
Authorization: Bearer {{CLOUDFLARE_TOKEN}}

###

# curl -X POST "https://api.cloudflare.com/client/v4/zones/[YOUR_ZONE_ID]/purge_cache"
#     -H "Authorization: Bearer [CLOUDFLARE_TOKEN]"
#     -H "Content-Type: application/json"
#     --data '{
#       "files": [
#         "https://example.com",
#         "https://example.com"
#       ]
#     }'
POST https://api.cloudflare.com/client/v4/zones/{{CLOUDFLARE_ZONE_ID}}/purge_cache
Authorization: Bearer {{CLOUDFLARE_TOKEN}}
Content-Type: application/json

{
  "files": [
    "https://dam.inspiraarte.com/preview/47.webp"
  ]
}




###
# curl -X POST "https://api.cloudflare.com/client/v4/zones/[YOUR_ZONE_ID]/purge_cache"
#     -H "Authorization: Bearer [CLOUDFLARE_TOKEN]"
#     -H "Content-Type: application/json"
#     --data '{"purge_everything":true}'
POST https://api.cloudflare.com/client/v4/zones/{{CLOUDFLARE_ZONE_ID}}/purge_cache
Authorization: Bearer {{CLOUDFLARE_TOKEN}}
Content-Type: application/json

{
  "purge_everything": true
}

###
